version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  cms:
    depends_on:
      - server
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - "5051:3000"
    env_file:
      - .env.docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
